"""The engine: the closed loop.

goal -> task graph -> pull-claim -> execute -> verify -> memory -> visibility -> learn

Single-agent baseline, pull-based, atomic claiming. No LLM calls — deterministic
rails. The host agent (or a future model-routing adapter) authors task specs; the
engine routes, executes, verifies, records, and learns.
"""
from __future__ import annotations

import uuid
from pathlib import Path

from . import (autonomy, effects, executors, memory, profiles, projectpack,
               quarantine, verify, waitpoints)
from .adapters import model as model_adapter
from .db import emit, init_db, jdumps, jloads, now

WORKER_ID = "worker-local-1"

# Executors whose actions have external side effects → routed through the effect
# ledger keyed by task id, so a retried task never double-applies.
SIDE_EFFECTING = {"shell", "python"}


def _is_side_effecting(kind, spec) -> bool:
    """A skill's `run` action executes an external script — a real side effect —
    so it goes through the ledger too (guidance is pure and does not)."""
    return kind in SIDE_EFFECTING or (kind == "skill" and spec.get("action") == "run")


def _id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:8]}"


# ---------------------------------------------------------------- goal intake ---
def create_goal(conn, title, description="", mode="general", tasks=None):
    gid = _id("g")
    ts = now()
    pdir = projectpack.project_dir(gid, title)
    conn.execute(
        "INSERT INTO goals (id,title,description,mode,status,project_dir,created_at,updated_at)"
        " VALUES (?,?,?,?,?,?,?,?)",
        (gid, title, description, mode, "active", str(pdir), ts, ts))
    conn.commit()
    emit(conn, "goal.created", goal_id=gid, title=title, mode=mode)

    specs = tasks if tasks is not None else decompose(title, description, mode)
    id_map = {}
    for spec in specs:
        tid = add_task(conn, gid, spec, id_map)
        id_map[spec.get("ref", tid)] = tid
    projectpack.render(conn, gid)
    return gid


def add_task(conn, goal_id, spec, id_map=None):
    id_map = id_map or {}
    tid = _id("t")
    ts = now()
    deps = [id_map.get(d, d) for d in spec.get("depends_on", [])]
    conn.execute(
        "INSERT INTO tasks (id,goal_id,title,kind,spec,skill_tags,status,depends_on,"
        "priority,risk,budget_ticks,attempts,max_attempts,verification,created_at,updated_at)"
        " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (tid, goal_id, spec["title"], spec["kind"], jdumps(spec.get("spec", {})),
         jdumps(spec.get("skill_tags", [])), "pending", jdumps(deps),
         spec.get("priority", 5), spec.get("risk", "low"),
         spec.get("budget_ticks", 1), 0, spec.get("max_attempts", 2),
         jdumps(spec.get("verification", {"type": "exec_ok"})), ts, ts))
    conn.commit()
    emit(conn, "task.created", goal_id=goal_id, task_id=tid, title=spec["title"], task_kind=spec["kind"])
    return tid


def decompose(title, description, mode):
    """Template decomposer (v1). Produces a real, verifiable plan-execute-verify
    graph so the loop has genuine work + independent checks. The host agent can
    override by passing explicit `tasks` to create_goal."""
    brief = (f"# {title}\n\n{description or 'No description provided.'}\n\n"
             f"Mode: {mode}\nGenerated by AgentOS decomposer.\n")
    return [
        {"ref": "gather", "title": "Gather context", "kind": "gather",
         "spec": {"note": f"Goal intake: {title}"},
         "verification": {"type": "file_exists", "path": "knowledge.md"},
         "skill_tags": ["research"], "priority": 1},
        {"ref": "build", "title": "Produce brief artifact", "kind": "write_file",
         "spec": {"path": "brief.md", "content": brief},
         "verification": {"type": "file_contains", "path": "brief.md", "needle": title},
         "depends_on": ["gather"], "skill_tags": ["writing"], "priority": 2},
        {"ref": "verify", "title": "Fan-in verification checkpoint", "kind": "checkpoint",
         "spec": {"note": "all artifacts present"},
         "verification": {"type": "command",
                          "cmd": "test -s knowledge.md && test -s artifacts/brief.md",
                          "expect_rc": 0},
         "depends_on": ["gather", "build"], "skill_tags": ["qa"], "priority": 3},
    ]


# ----------------------------------------------------------------- the tick ----
def _eligible_task(conn, goal_id=None):
    q = "SELECT * FROM tasks WHERE status='pending'"
    args = []
    if goal_id:
        q += " AND goal_id=?"
        args.append(goal_id)
    q += " ORDER BY priority, created_at"
    for t in conn.execute(q, args).fetchall():
        deps = jloads(t["depends_on"], [])
        if not deps:
            return t
        done = conn.execute(
            "SELECT COUNT(*) c FROM tasks WHERE id IN (%s) AND status='done'"
            % ",".join("?" * len(deps)), deps).fetchone()["c"]
        if done == len(deps):
            return t
    return None


def _claim(conn, task_id, worker_id=WORKER_ID) -> bool:
    """Atomic pull-based claim: only one worker can move pending->claimed. This
    single UPDATE…WHERE status='pending' is what makes multiple workers (threads
    or machines) safe on one task graph — exactly one gets rowcount==1."""
    cur = conn.execute(
        "UPDATE tasks SET status='claimed', worker=?, updated_at=? "
        "WHERE id=? AND status='pending'", (worker_id, now(), task_id))
    conn.commit()
    return cur.rowcount == 1


def resume_ready_waits(conn, goal_id=None):
    """Flip blocked `wait` tasks whose waitpoint is now satisfied back to pending,
    so a later tick (even in a fresh process) resumes them from their waitpoint."""
    q = "SELECT * FROM tasks WHERE status='blocked' AND kind='wait'"
    args = []
    if goal_id:
        q += " AND goal_id=?"
        args.append(goal_id)
    for t in conn.execute(q, args).fetchall():
        wp = waitpoints.for_task(conn, t["id"])
        if wp and waitpoints.ready(conn, wp):
            conn.execute("UPDATE tasks SET status='pending', updated_at=? WHERE id=?",
                         (now(), t["id"]))
            conn.commit()
            emit(conn, "task.wait_ready", goal_id=t["goal_id"], task_id=t["id"])


def _handle_wait(conn, t, spec) -> dict:
    """A `wait` task: create a waitpoint and block, or resolve it and complete."""
    tid = t["id"]
    wp = waitpoints.for_task(conn, tid)
    if wp is None:
        kind = spec.get("wait", "signal")
        wp_id = waitpoints.create(conn, tid, t["goal_id"], kind,
                                  wake_at=spec.get("until", ""), signal=spec.get("signal", ""),
                                  reason=spec.get("reason", f"{kind} wait"))
        wp = conn.execute("SELECT * FROM waitpoints WHERE id=?", (wp_id,)).fetchone()
    if waitpoints.ready(conn, wp):
        waitpoints.resolve(conn, wp["id"])
        conn.execute("UPDATE tasks SET status='done', evidence=?, updated_at=? WHERE id=?",
                     (jdumps({"waited": wp["kind"]}), now(), tid))
        conn.commit()
        emit(conn, "task.resumed", goal_id=t["goal_id"], task_id=tid, wp_kind=wp["kind"])
        memory.record(conn, "episodic", f"task.resumed:{tid}", f"{t['title']} resumed from {wp['kind']} wait",
                      provenance=f"task:{tid}", confidence=0.9)
        _update_goal_status(conn, t["goal_id"])
        projectpack.render(conn, t["goal_id"])
        return {"task_id": tid, "title": t["title"], "result": "done", "verified": True}
    conn.execute("UPDATE tasks SET status='blocked', updated_at=? WHERE id=?", (now(), tid))
    conn.commit()
    emit(conn, "task.waiting", goal_id=t["goal_id"], task_id=tid, wp_kind=wp["kind"])
    projectpack.render(conn, t["goal_id"])
    return {"task_id": tid, "title": t["title"], "result": "waiting", "wp_kind": wp["kind"]}


def tick(conn, goal_id=None, worker_id=WORKER_ID) -> dict | None:
    """Advance the loop by one task. Returns an outcome dict, or None if idle."""
    resume_ready_waits(conn, goal_id)
    t = _eligible_task(conn, goal_id)
    if not t:
        return None
    tid = t["id"]
    if not _claim(conn, tid, worker_id):
        return {"task_id": tid, "result": "claim-lost"}

    if t["kind"] == "wait":
        return _handle_wait(conn, t, jloads(t["spec"], {}))

    # route: pick a behavior profile + a model tier for this task (M2 seam).
    tags = jloads(t["skill_tags"], [])
    profile = profiles.route_profile(t["kind"], tags)
    trust = _task_trust(conn, tags)
    routing = model_adapter.route(profile, t["risk"])
    emit(conn, "task.routed", goal_id=t["goal_id"], task_id=tid,
         profile=profile.get("name"), model=routing["model"], trust=round(trust, 3))

    # trust- and risk-gated autonomy: pause for human approval when not earned.
    needs_approval, reason = autonomy.decide(t["risk"], trust, t["kind"])
    if needs_approval:
        existing = conn.execute(
            "SELECT status FROM approvals WHERE task_id=? ORDER BY id DESC LIMIT 1",
            (tid,)).fetchone()
        if not existing or existing["status"] == "pending":
            if not existing:
                conn.execute("INSERT INTO approvals (ts,task_id,reason,status) VALUES (?,?,?,?)",
                             (now(), tid, reason, "pending"))
                conn.commit()
            conn.execute("UPDATE tasks SET status='blocked', updated_at=? WHERE id=?", (now(), tid))
            conn.commit()
            emit(conn, "task.awaiting_approval", goal_id=t["goal_id"], task_id=tid, reason=reason)
            projectpack.render(conn, t["goal_id"])
            return {"task_id": tid, "result": "awaiting_approval", "reason": reason}
        if existing["status"] == "denied":
            return _fail(conn, t, "approval denied")
        # else: approved — fall through and execute.

    conn.execute("UPDATE tasks SET status='running', attempts=attempts+1, updated_at=? WHERE id=?",
                 (now(), tid))
    conn.commit()
    emit(conn, "task.running", goal_id=t["goal_id"], task_id=tid)
    rid = conn.execute("INSERT INTO runs (task_id, started, cost_ticks) VALUES (?,?,?)",
                       (tid, now(), routing["cost"])).lastrowid
    conn.commit()

    project_dir = Path(conn.execute("SELECT project_dir FROM goals WHERE id=?",
                                    (t["goal_id"],)).fetchone()["project_dir"])
    spec = jloads(t["spec"], {})
    plan = jloads(t["verification"], {"type": "exec_ok"})

    # reuse procedural memory if a matching recipe exists (memory-reuse metric)
    memory.find_recipe(conn, t["kind"], plan.get("type", "exec_ok"))

    if _is_side_effecting(t["kind"], spec):
        # idempotent: a committed side effect is replayed on retry, not re-run
        result = effects.guarded(conn, f"task:{tid}", t["kind"],
                                 lambda: executors.run_executor(t["kind"], spec, project_dir))
    else:
        result = executors.run_executor(t["kind"], spec, project_dir)
    passed, evidence = verify.verify(plan, result, project_dir)

    conn.execute("UPDATE runs SET finished=?, ok=?, verified=?, output=? WHERE id=?",
                 (now(), int(bool(result["ok"])), int(passed),
                  result.get("output", "")[:8000], rid))
    conn.commit()

    # refresh attempts count
    t = conn.execute("SELECT * FROM tasks WHERE id=?", (tid,)).fetchone()

    if passed:
        conn.execute("UPDATE tasks SET status='done', evidence=?, artifacts=?, updated_at=? WHERE id=?",
                     (jdumps(evidence), jdumps(result.get("artifacts", [])), now(), tid))
        conn.commit()
        emit(conn, "task.done", goal_id=t["goal_id"], task_id=tid, evidence=evidence)
        memory.record(conn, "episodic", f"task.done:{tid}",
                      f"{t['title']} verified ({plan.get('type')})",
                      provenance=f"task:{tid}", confidence=0.9)
        memory.record_procedural(conn, t, result)
        _learn_success(conn, t)
    else:
        if t["attempts"] < t["max_attempts"]:
            conn.execute("UPDATE tasks SET status='pending', escalation=?, updated_at=? WHERE id=?",
                         (f"retry: {result.get('output','')[:200]}", now(), tid))
            conn.commit()
            emit(conn, "task.retry", goal_id=t["goal_id"], task_id=tid, evidence=evidence)
            projectpack.render(conn, t["goal_id"])
            return {"task_id": tid, "result": "retry", "verified": False}
        return _fail(conn, t, f"verification failed ({plan.get('type')})", evidence)

    _update_goal_status(conn, t["goal_id"])
    projectpack.render(conn, t["goal_id"])
    return {"task_id": tid, "title": t["title"], "result": "done", "verified": True,
            "evidence": evidence}


def _fail(conn, t, reason, evidence=None):
    tid = t["id"]
    conn.execute("UPDATE tasks SET status='failed', escalation=?, evidence=?, updated_at=? WHERE id=?",
                 (reason, jdumps(evidence or {}), now(), tid))
    conn.commit()
    emit(conn, "task.failed", goal_id=t["goal_id"], task_id=tid, reason=reason)
    memory.record(conn, "episodic", f"task.failed:{tid}", f"{t['title']}: {reason}",
                  provenance=f"task:{tid}", confidence=0.9)
    quarantine.record(conn, t, reason, evidence)   # dead-letter with evidence bundle
    _maybe_compensate(conn, t)                      # no orphaned side effects
    _learn_failure(conn, t, reason)
    _update_goal_status(conn, t["goal_id"])
    projectpack.render(conn, t["goal_id"])
    return {"task_id": tid, "title": t["title"], "result": "failed", "reason": reason}


def _maybe_compensate(conn, t):
    """If a failed task left a committed side effect, undo it. The task can declare
    `on_fail_compensate` (an executor spec). If it can't, we emit
    compensation.required (the trace judge surfaces it) — never pretend to undo."""
    key = f"task:{t['id']}"
    if effects.status(conn, key) != "committed":
        return
    spec = jloads(t["spec"], {})
    comp = spec.get("on_fail_compensate")
    if not comp:
        emit(conn, "compensation.required", goal_id=t["goal_id"], task_id=t["id"])
        return
    project_dir = Path(conn.execute("SELECT project_dir FROM goals WHERE id=?",
                                    (t["goal_id"],)).fetchone()["project_dir"])
    res = executors.run_executor(comp["kind"], comp, project_dir)
    if res.get("ok"):
        effects.compensate(conn, key)              # undo already applied → mark compensated
        emit(conn, "task.compensated", goal_id=t["goal_id"], task_id=t["id"])
    else:
        emit(conn, "compensation.failed", goal_id=t["goal_id"], task_id=t["id"],
             output=res.get("output", "")[:200])


def _update_goal_status(conn, goal_id):
    rows = conn.execute("SELECT status, COUNT(*) c FROM tasks WHERE goal_id=? GROUP BY status",
                        (goal_id,)).fetchall()
    counts = {r["status"]: r["c"] for r in rows}
    total = sum(counts.values())
    if counts.get("done", 0) == total and total > 0:
        status = "done"
    elif counts.get("failed", 0) and not (counts.get("pending", 0) + counts.get("running", 0)
                                          + counts.get("claimed", 0)):
        status = "failed"
    else:
        status = "active"
    conn.execute("UPDATE goals SET status=?, updated_at=? WHERE id=?", (status, now(), goal_id))
    conn.commit()
    if status in ("done", "failed"):
        emit(conn, f"goal.{status}", goal_id=goal_id)


def run(conn, goal_id=None, max_ticks=100, worker_id=WORKER_ID) -> list[dict]:
    outcomes = []
    for _ in range(max_ticks):
        out = tick(conn, goal_id, worker_id)
        if out is None:
            break
        outcomes.append(out)
        if out.get("result") == "awaiting_approval":
            break
    return outcomes


# ------------------------------------------------------------------- learning --
def _learn_success(conn, t):
    """Inline learning after success: reinforce the recipe (done in record_procedural)
    and bump per-skill trust."""
    for tag in jloads(t["skill_tags"], []):
        _bump_trust(conn, tag, +0.03)


def _learn_failure(conn, t, reason):
    """Failure loop: convert a repeated same-shape failure into an eval case +
    drop trust. If this exact (kind, reason-shape) failed before, flag it."""
    for tag in jloads(t["skill_tags"], []):
        _bump_trust(conn, tag, -0.05)
    key = f"failure:{t['kind']}"
    prior = conn.execute("SELECT id, uses FROM memory WHERE mtype='semantic' AND mkey=?",
                         (key,)).fetchone()
    if prior:
        conn.execute("UPDATE memory SET uses=uses+1 WHERE id=?", (prior["id"],))
        conn.commit()
        # second occurrence -> guardrail: register an eval candidate
        memory.record(conn, "semantic", f"eval_candidate:{t['kind']}",
                      f"Recurring failure for kind={t['kind']}: {reason}. Add a regression eval.",
                      tags=["eval", "guardrail"], provenance=f"task:{t['id']}", confidence=0.8)
    else:
        memory.record(conn, "semantic", key, f"first failure for kind={t['kind']}: {reason}",
                      provenance=f"task:{t['id']}", confidence=0.6)


def _task_trust(conn, skill_tags) -> float:
    """A task is only as trusted as its least-trusted skill. Default 0.5 (neutral)."""
    tags = skill_tags or []
    if not tags:
        return 0.5
    vals = []
    for tag in tags:
        row = conn.execute("SELECT value FROM memory WHERE mtype='preference' AND mkey=?",
                           (f"trust:{tag}",)).fetchone()
        vals.append(float(row["value"]) if row else 0.5)
    return min(vals)


def _bump_trust(conn, skill, delta):
    key = f"trust:{skill}"
    row = conn.execute("SELECT id, value FROM memory WHERE mtype='preference' AND mkey=?",
                       (key,)).fetchone()
    if row:
        val = max(0.0, min(1.0, float(row["value"]) + delta))
        conn.execute("UPDATE memory SET value=?, ts=? WHERE id=?", (f"{val:.3f}", now(), row["id"]))
    else:
        memory.record(conn, "preference", key, f"{max(0.0, min(1.0, 0.5 + delta)):.3f}",
                      tags=["trust", skill], provenance="trust-loop")
    conn.commit()


# -------------------------------------------------------------------- metrics --
def metrics(conn) -> dict:
    g = lambda q, *a: conn.execute(q, a).fetchone()[0]
    tasks_total = g("SELECT COUNT(*) FROM tasks")
    tasks_done = g("SELECT COUNT(*) FROM tasks WHERE status='done'")
    tasks_failed = g("SELECT COUNT(*) FROM tasks WHERE status='failed'")
    runs_total = g("SELECT COUNT(*) FROM runs")
    runs_verified = g("SELECT COUNT(*) FROM runs WHERE verified=1")
    retries = g("SELECT COUNT(*) FROM events WHERE kind='task.retry'")
    approvals = g("SELECT COUNT(*) FROM events WHERE kind='task.awaiting_approval'")
    eval_total = g("SELECT COUNT(*) FROM evals")
    eval_pass = g("SELECT COUNT(*) FROM evals WHERE passed=1")
    return {
        "tasks_total": tasks_total,
        "tasks_completed": tasks_done,
        "tasks_verified": runs_verified,
        "tasks_failed": tasks_failed,
        "retry_rate": round(retries / runs_total, 3) if runs_total else 0.0,
        "intervention_rate": round(approvals / tasks_total, 3) if tasks_total else 0.0,
        "eval_pass_rate": round(eval_pass / eval_total, 3) if eval_total else 0.0,
        "memory_reuse": round(memory.reuse_rate(conn), 3),
        "cost_ticks": g("SELECT COALESCE(SUM(cost_ticks),0) FROM runs"),
    }
